apiVersion: v1
kind: Service
metadata:
  name: kokoro-service
spec:
  selector:
    app: kokoro-tts
  ports:
    - protocol: TCP
      port: 8880
      targetPort: 8880
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kokoro-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kokoro-tts
  template:
    metadata:
      labels:
        app: kokoro-tts
    spec:
      containers:
      - name: kokoro-container
        image: ghcr.io/remsky/kokoro-fastapi-gpu:v0.2.2
        ports:
        - containerPort: 8880
        resources:
          limits:
            memory: "8Gi"     
            cpu: "4"          
            nvidia.com/gpu: 1  
          requests:
            memory: "8Gi"     
            cpu: "4"         
            nvidia.com/gpu: 1
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
